saber/funcs/impl/cuda/base/sass/README.md

add sass README

---

framework/operators/embedding.cpp
framework/operators/embedding.h
framework/operators/scale.cpp
framework/operators/scale.h
saber/funcs/embedding.h
saber/funcs/impl/cuda/base/cuda_c/saber_embedding.cu
saber/funcs/impl/cuda/base/cuda_c/saber_scale.cu
saber/funcs/impl/cuda/saber_embedding.h
saber/funcs/impl/cuda/saber_scale.h
saber/funcs/impl/impl_embedding.h
saber/funcs/impl/impl_scale.h
saber/funcs/impl/x86/saber_embedding.cpp
saber/funcs/impl/x86/saber_embedding.h
saber/funcs/impl/x86/saber_scale.cpp
saber/funcs/impl/x86/saber_scale.h
saber/funcs/scale.h
saber/saber_funcs_param.h
test/saber/cuda/test_saber_func_embedding.cpp
test/saber/cuda/test_saber_func_scale.cpp
test/saber/x86/test_saber_func_embedding_x86.cpp
test/saber/x86/test_saber_func_scale_x86.cpp

update embedding and scale

---

saber/funcs/impl/cuda/saber_fc.h
saber/funcs/impl/cuda/vender_conv.h
saber/funcs/impl/cuda/vender_conv_act.h
saber/funcs/impl/cuda/vender_conv_act_pooling.h

This pr fixes some destructor function bugs(vender conv, vender conv_act, vender conv_act_pooling).

fix destructor function bugs

---

saber/funcs/impl/arm/saber_conv_act.h
saber/funcs/impl/arm/saber_eltwise.cpp
saber/funcs/impl/arm/saber_eltwise.h
saber/funcs/impl/arm/saber_fc.h
saber/funcs/impl/arm/saber_permute.cpp
saber/funcs/impl/arm/saber_prelu.cpp

fix saber arm build error, now can generate dynamic lib of saber

fix saber arm build error

---

.coveralls.yml
.travis.yml
README.md

add .travis.yml
add Build Status in README.md

 add .travis.yml and add Build Status in README.md

---

framework/core/net/net.cpp
framework/operators/concat.cpp
framework/operators/crf_decoding.cpp
framework/operators/crf_decoding.h
framework/operators/dense.cpp
framework/operators/embedding.cpp
framework/operators/gru.cpp
framework/operators/input.cpp
framework/operators/sequence_pool.cpp
framework/operators/sequence_pool.h
framework/operators/split.cpp
saber/funcs/concat.h
saber/funcs/fc.h
saber/funcs/impl/detection_helper.h
saber/funcs/impl/x86/saber_concat.cpp
saber/funcs/impl/x86/saber_concat.h
saber/funcs/impl/x86/saber_crf_decoding.cpp
saber/funcs/impl/x86/saber_gru.cpp
saber/funcs/impl/x86/vender_fc.cpp
test/framework/net/chinese_ner_test.cpp

Add X86 ops in framework(sequence pool, crf_decoding)
crf_decoding alias name: CrfDecoding
sequence_pool alias name: SequencePool

X86 ner model pass

---

.travis.yml

modify .travis.yml only for NVIDIA_GPU build

modify .travis.yml only for NVIDIA_GPU build

---

docs/Manual/addCustomOp.md

add custom op document

---

tools/external_converter_v2/config.py
tools/external_converter_v2/parser/graph.py
tools/external_converter_v2/parser/graph_io.py
tools/external_converter_v2/parser/graph_to_json.py
tools/external_converter_v2/parser/kill_caffe/caffe_layer_param_transmit.py
tools/external_converter_v2/parser/kill_caffe/parser_caffe.py
tools/external_converter_v2/parser/kill_fluid/__init__.py
tools/external_converter_v2/parser/kill_fluid/fluid_debugger.py
tools/external_converter_v2/parser/kill_fluid/fluid_helper.py
tools/external_converter_v2/parser/kill_fluid/fluid_layer_param_transmit.py
tools/external_converter_v2/parser/kill_fluid/parser_fluid.py
tools/external_converter_v2/parser/operations/__init__.py
tools/external_converter_v2/parser/operations/op.py
tools/external_converter_v2/parser/operations/ops.py
tools/external_converter_v2/parser/operations/ops_fluid.py
tools/external_converter_v2/parser/pbs/__init__.py
tools/external_converter_v2/parser/proto/node.proto
tools/external_converter_v2/parser/proto/operator.proto

1、首先支持 vis 业务线的 bodydetect / ocr 解析；
2、原有 Caffe 解析不变

加入 Fluid Parser

---

saber/funcs/impl/cuda/saber_conv_act.h
saber/funcs/impl/cuda/saber_conv_act_pooling.h

fix conv_act batch bugs, fix conv_act_pooling init bugs

fix model bugs

---

benchmark/README_CPU.md

update CPU benchmark from QA report

update CPU benchmark from QA report

---

AUTHORS.md

add authors

---

.travis.yml
docker/AMD/centos/centos7-rocm-opencl/Dockerfile
docker/README.md
docker/anakin_docker_build_and_run.sh
docs/Manual/INSTALL_en.md
examples/CMakeLists.txt
examples/amd/classification.cpp
framework/operators/softmax.cpp
saber/core/impl/amd/tensor_op_amd.cpp
saber/funcs/impl/amd/saber_conv.cpp
saber/funcs/impl/amd/saber_conv_act.cpp
saber/funcs/impl/amd/saber_softmax.cpp
test/saber/amd/test_saber_func_activation_AMD.cpp
test/saber/amd/test_saber_func_conv_AMD.cpp
test/saber/amd/test_saber_func_softmax_AMD.cpp
tools/amd_gpu_build.sh

8 commits 
1. AMD docker and README updated
Need to modify the git URL in Dockerfile when this patch is merged to another branch, such as merged to branch : developing.
2. INSTALL_en README for AMD part.
3. Add slope to activation unit test
4. Fix issue in conv_act for wrong arguments
5. add example of classification.
6. force use saber_softmax for AMD platform
7 Add mult-batch solution for softmax
8 Add profiling in softmax

Amd update

---

saber/funcs/deconv_act.h

missing a function include file

fix bug in deconv_act

---

saber/funcs/base.h
saber/funcs/impl/cuda/saber_conv_act.h
saber/funcs/impl/cuda/saber_conv_act_pooling.h

修复：
1、网络运行前 tensor reshape 的问题；
2、conv_act 融合结果不正确的问题；
3、conv_act_pooling 同步点的问题。

针对 ocr 模型的修改

---

saber/funcs/impl/x86/activation_functions.h
saber/funcs/impl/x86/saber_normal_activation.h
saber/funcs/impl/x86/vender_gru.cpp
saber/funcs/impl/x86/vender_lstm.cpp

Developing fix compile without avx2

Developing fix compile without avx2

---

test/framework/net/test_map_rnn.cpp

udpate a bug in test code

---

saber/funcs/power.h

fix power bug

---

saber/saber_funcs_param.h

add param dev_v2

---

tools/anakin-lite/CMakeLists.txt

 set install path to specified os and arch

---

saber/funcs/impl/cuda/base/cuda_c/saber_gru.cu

fix gru run ocr bug

---

test/saber/test_saber_base.h

fix test_base

---

test/saber/test_saber_reshape.cpp

add X86 reshape ut

---

saber/funcs/impl/cuda/base/cuda_c/saber_reverse_input.cu
saber/funcs/impl/cuda/base/cuda_c/saber_reverse_sequence.cu
saber/funcs/impl/cuda/saber_reverse_input.h
saber/funcs/impl/cuda/saber_reverse_sequence.h
saber/funcs/impl/impl_reverse_input.h
saber/funcs/impl/impl_reverse_sequence.h
saber/funcs/impl/x86/saber_reverse_input.cpp
saber/funcs/impl/x86/saber_reverse_input.h
saber/funcs/impl/x86/saber_reverse_sequence.cpp
saber/funcs/impl/x86/saber_reverse_sequence.h
saber/funcs/reverse_input.h
saber/funcs/reverse_sequence.h
saber/saber_funcs_param.h
test/saber/test_saber_reverse_input.cpp
test/saber/test_saber_reverse_sequence.cpp

dev_v2 reverse input sequence

---

saber/funcs/conv_unpadding_padding.h
saber/funcs/impl/cuda/base/cuda_c/saber_conv_upadding_padding.cu
saber/funcs/impl/cuda/saber_conv_upadding_padding.h
saber/funcs/impl/impl_conv_unpadding_padding.h
saber/saber_funcs_param.h
test/saber/test_saber_conv_unpadding_padding.cpp

Dev v2 conv unpadding padding

---

saber/funcs/activation.h
saber/funcs/conv.h
test/saber/test_saber_activation.cpp
test/saber/test_saber_conv.cpp

remove bm ut

---

cmake/compiler_options.cmake
cmake/external/xbyak.cmake
framework/core/functor.h
framework/core/net/net.cpp
framework/graph/llvm/scheduler.cpp
saber/CMakeLists.txt
saber/funcs/impl/x86/vender_fc.cpp
saber/funcs/impl/x86/vender_fc.h
sgx/CMakeLists.txt
third-party/xbyak.patch

Currently, the SGX target won't compile due to several errors. This PR fixes these errors.

Fix SGX build failure

---

README.md
saber/core/impl/arm/arm_device.cpp
saber/funcs/impl/arm/neon/impl/sgemm_arm.cpp
saber/funcs/impl/arm/neon/impl/sgemm_arm.h
saber/funcs/impl/arm/neon/impl/sgemm_prepacked.cpp

add License
